export enum ActionType {
  SET_MESSAGE = "SET_MESSAGE",
  SET_MESSAGE_SHOW = "SET_SHOW_MESSAGE",
  SET_USER = "SET_USER",
  UNSET_USER = "UNSET_USER",
  ADD_PROGRESS_ITEM = "ADD_PROGRESS_ITEM",
  REMOVE_PROGRESS_ITEM = "REMOVE_PROGRESS_ITEM",
  UPDATE_PROGRESS_ITEM = "UPDATE_PROGRESS_ITEM",
  TOGGLE_PROGRESS_ITEM = "TOGGLE_PROGRESS_ITEM",
  ADD_NOFITICATION_ITEM = "ADD_NOFITICATION_ITEM",
  REMOVE_NOFITICATION_ITEM = "REMOVE_NOFITICATION_ITEM",
  REMOVEALL_NOFITICATION_ITEM = "REMOVEALL_NOFITICATION_ITEM",
}
