import { useState } from "react";
import { Box, Grid, Icon, InputAdornment, TextField, Typography } from "@mui/material";
import type { NextPage } from "next";
import Head from "next/head";
import * as Icons from "@dhi/icons";
import { IconGrid, StyledSearchContainer } from "../styles/styles";

const IconsPage: NextPage = () => {
  const iconNames = [
    { title: "AddData", icon: Icons.AddData },
    { title: "AddLayer", icon: Icons.AddLayer },
    { title: "AddList", icon: Icons.AddList },
    { title: "AddResultItems", icon: Icons.AddResultItems },
    { title: "AddToMesh", icon: Icons.AddToMesh },
    { title: "Adjust", icon: Icons.Adjust },
    { title: "Admin", icon: Icons.Admin },
    { title: "AdminSettings", icon: Icons.AdminSettings },
    { title: "Alarm", icon: Icons.Alarm },
    { title: "Alert", icon: Icons.Alert },
    { title: "AllProjects", icon: Icons.AllProjects },
    { title: "Analysis", icon: Icons.Analysis },
    { title: "Analyze", icon: Icons.Analyze },
    { title: "Apps", icon: Icons.Apps },
    { title: "Archive", icon: Icons.Archive },
    { title: "Area", icon: Icons.Area },
    { title: "AreaChart", icon: Icons.AreaChart },
    { title: "AreaInfo", icon: Icons.AreaInfo },
    { title: "ArrowDown", icon: Icons.ArrowDown },
    { title: "ArrowLeft", icon: Icons.ArrowLeft },
    { title: "ArrowRight", icon: Icons.ArrowRight },
    { title: "ArrowUp", icon: Icons.ArrowUp },
    { title: "Attach", icon: Icons.Attach },
    { title: "BackgroundMap", icon: Icons.BackgroundMap },
    { title: "BatchSimulation", icon: Icons.BatchSimulation },
    { title: "Block", icon: Icons.Block },
    { title: "Bookmark", icon: Icons.Bookmark },
    { title: "BoundaryLine", icon: Icons.BoundaryLine },
    { title: "BoundaryLineCheck", icon: Icons.BoundaryLineCheck },
    { title: "Business", icon: Icons.Business },
    { title: "Calendar", icon: Icons.Calendar },
    { title: "CalendarSetting", icon: Icons.CalendarSetting },
    { title: "Cart", icon: Icons.Cart },
    { title: "Center", icon: Icons.Center },
    { title: "Checkmark", icon: Icons.Checkmark },
    { title: "ClearFilters", icon: Icons.ClearFilters },
    { title: "ClearFlag", icon: Icons.ClearFlag },
    { title: "ClearSelection", icon: Icons.ClearSelection },
    { title: "Clip", icon: Icons.Clip },
    { title: "ClipSelection", icon: Icons.ClipSelection },
    { title: "Clone", icon: Icons.Clone },
    { title: "Close", icon: Icons.Close },
    { title: "CloseS", icon: Icons.CloseS },
    { title: "CloseXs", icon: Icons.CloseXs },
    { title: "CloudExport", icon: Icons.CloudExport },
    { title: "ColorCircle", icon: Icons.ColorCircle },
    { title: "Comment", icon: Icons.Comment },
    { title: "ConfidentialProject", icon: Icons.ConfidentialProject },
    { title: "ConnectedData", icon: Icons.ConnectedData },
    { title: "ConnectFlag", icon: Icons.ConnectFlag },
    { title: "Connection", icon: Icons.Connection },
    { title: "Connections", icon: Icons.Connections },
    { title: "ConnectionsAlt", icon: Icons.ConnectionsAlt },
    { title: "ConnectionTool", icon: Icons.ConnectionTool },
    { title: "ConvertData", icon: Icons.ConvertData },
    { title: "CopyLink", icon: Icons.CopyLink },
    { title: "CornerHandle", icon: Icons.CornerHandle },
    { title: "CreateNewMesh", icon: Icons.CreateNewMesh },
    { title: "Crosshair", icon: Icons.Crosshair },
    { title: "Dashboard", icon: Icons.Dashboard },
    { title: "DatabaseTransfer", icon: Icons.DatabaseTransfer },
    { title: "DataConfiguration", icon: Icons.DataConfiguration },
    { title: "DataSet", icon: Icons.DataSet },
    { title: "DefaultValue", icon: Icons.DefaultValue },
    { title: "DefaultView", icon: Icons.DefaultView },
    { title: "Delete", icon: Icons.Delete },
    { title: "DeleteLastPoint", icon: Icons.DeleteLastPoint },
    { title: "DhiWave", icon: Icons.DhiWave },
    { title: "Dialogue", icon: Icons.Dialogue },
    { title: "Distance", icon: Icons.Distance },
    { title: "Document", icon: Icons.Document },
    { title: "Documentation", icon: Icons.Documentation },
    { title: "Dollar", icon: Icons.Dollar },
    { title: "Down", icon: Icons.Down },
    { title: "Download", icon: Icons.Download },
    { title: "DownS", icon: Icons.DownS },
    { title: "DownTriangle", icon: Icons.DownTriangle },
    { title: "Drag", icon: Icons.Drag },
    { title: "DragHandle", icon: Icons.DragHandle },
    { title: "Draw", icon: Icons.Draw },
    { title: "DrawCircle", icon: Icons.DrawCircle },
    { title: "DrawDikes", icon: Icons.DrawDikes },
    { title: "DrawDitches", icon: Icons.DrawDitches },
    { title: "DrawPolygon", icon: Icons.DrawPolygon },
    { title: "DrawRectangle", icon: Icons.DrawRectangle },
    { title: "Duplicate", icon: Icons.Duplicate },
    { title: "Edit", icon: Icons.Edit },
    { title: "EditGrid", icon: Icons.EditGrid },
    { title: "EditMeshSettings", icon: Icons.EditMeshSettings },
    { title: "EditSelection", icon: Icons.EditSelection },
    { title: "EditSelections", icon: Icons.EditSelections },
    { title: "Email", icon: Icons.Email },
    { title: "Emoticon", icon: Icons.Emoticon },
    { title: "Equal", icon: Icons.Equal },
    { title: "Eraser", icon: Icons.Eraser },
    { title: "ExagerateElevation", icon: Icons.ExagerateElevation },
    { title: "Exit", icon: Icons.Exit },
    { title: "Expand", icon: Icons.Expand },
    { title: "Extract", icon: Icons.Extract },
    { title: "Extracting", icon: Icons.Extracting },
    { title: "EyeHidden", icon: Icons.EyeHidden },
    { title: "EyeVisible", icon: Icons.EyeVisible },
    { title: "Fast", icon: Icons.Fast },
    { title: "FastForward", icon: Icons.FastForward },
    { title: "FileInfo", icon: Icons.FileInfo },
    { title: "FileWarning", icon: Icons.FileWarning },
    { title: "Fill", icon: Icons.Fill },
    { title: "Filter", icon: Icons.Filter },
    { title: "FilterSelection", icon: Icons.FilterSelection },
    { title: "FinePrint", icon: Icons.FinePrint },
    { title: "Flag", icon: Icons.Flag },
    { title: "Flags", icon: Icons.Flags },
    { title: "Flowchart", icon: Icons.Flowchart },
    { title: "Folder", icon: Icons.Folder },
    { title: "FolderZip", icon: Icons.FolderZip },
    { title: "Forefront", icon: Icons.Forefront },
    { title: "ForefrontAlt", icon: Icons.ForefrontAlt },
    { title: "Geometry", icon: Icons.Geometry },
    { title: "Gis", icon: Icons.Gis },
    { title: "GoogleWebSearch", icon: Icons.GoogleWebSearch },
    { title: "GoToEnd", icon: Icons.GoToEnd },
    { title: "GoToStart", icon: Icons.GoToStart },
    { title: "Grid", icon: Icons.Grid },
    { title: "GridCircle", icon: Icons.GridCircle },
    { title: "Group", icon: Icons.Group },
    { title: "Heatmap", icon: Icons.Heatmap },
    { title: "Highlighted", icon: Icons.Highlighted },
    { title: "HighlightedOff", icon: Icons.HighlightedOff },
    { title: "HighlightedOn", icon: Icons.HighlightedOn },
    { title: "History", icon: Icons.History },
    { title: "Hole", icon: Icons.Hole },
    { title: "Home", icon: Icons.Home },
    { title: "Icon", icon: Icons.Icon },
    { title: "Info", icon: Icons.Info },
    { title: "Inspect", icon: Icons.Inspect },
    { title: "InvertSelection", icon: Icons.InvertSelection },
    { title: "IsolationMode", icon: Icons.IsolationMode },
    { title: "ItemSettings", icon: Icons.ItemSettings },
    { title: "Join", icon: Icons.Join },
    { title: "Language", icon: Icons.Language },
    { title: "Layer", icon: Icons.Layer },
    { title: "Layers", icon: Icons.Layers },
    { title: "Learning", icon: Icons.Learning },
    { title: "Left", icon: Icons.Left },
    { title: "LeftNarrow", icon: Icons.LeftNarrow },
    { title: "LeftS", icon: Icons.LeftS },
    { title: "LessThan", icon: Icons.LessThan },
    { title: "LineChart", icon: Icons.LineChart },
    { title: "Lines", icon: Icons.Lines },
    { title: "Link", icon: Icons.Link },
    { title: "LinkedProject", icon: Icons.LinkedProject },
    { title: "ListView", icon: Icons.ListView },
    { title: "Lock", icon: Icons.Lock },
    { title: "Loop", icon: Icons.Loop },
    { title: "MainPanel", icon: Icons.MainPanel },
    { title: "MapPinFilled", icon: Icons.MapPinFilled },
    { title: "MapPinOutline", icon: Icons.MapPinOutline },
    { title: "MapView", icon: Icons.MapView },
    { title: "Measure", icon: Icons.Measure },
    { title: "MedialAxis", icon: Icons.MedialAxis },
    { title: "Menu", icon: Icons.Menu },
    { title: "Merge", icon: Icons.Merge },
    { title: "Mesh", icon: Icons.Mesh },
    { title: "MeshCollection", icon: Icons.MeshCollection },
    { title: "MeshColors", icon: Icons.MeshColors },
    { title: "MeshOperation", icon: Icons.MeshOperation },
    { title: "MeshPlay", icon: Icons.MeshPlay },
    { title: "MeshSettings", icon: Icons.MeshSettings },
    { title: "Metrics", icon: Icons.Metrics },
    { title: "Minimize", icon: Icons.Minimize },
    { title: "Minus", icon: Icons.Minus },
    { title: "Model3d", icon: Icons.Model3d },
    { title: "More", icon: Icons.More },
    { title: "MoreThan", icon: Icons.MoreThan },
    { title: "MouseClick", icon: Icons.MouseClick },
    { title: "Move", icon: Icons.Move },
    { title: "MsProject", icon: Icons.MsProject },
    { title: "MultipleChoice", icon: Icons.MultipleChoice },
    { title: "MyProjects", icon: Icons.MyProjects },
    { title: "MySql", icon: Icons.MySql },
    { title: "Mystery", icon: Icons.Mystery },
    { title: "Navigate", icon: Icons.Navigate },
    { title: "NestedTools", icon: Icons.NestedTools },
    { title: "NewDocument", icon: Icons.NewDocument },
    { title: "NewProject", icon: Icons.NewProject },
    { title: "North", icon: Icons.North },
    { title: "Note", icon: Icons.Note },
    { title: "NotHole", icon: Icons.NotHole },
    { title: "NotificationAlert", icon: Icons.NotificationAlert },
    { title: "NotificationBell", icon: Icons.NotificationBell },
    { title: "Opacity", icon: Icons.Opacity },
    { title: "Open", icon: Icons.Open },
    { title: "OpenInEditor", icon: Icons.OpenInEditor },
    { title: "Operations", icon: Icons.Operations },
    { title: "Overlap", icon: Icons.Overlap },
    { title: "Pan", icon: Icons.Pan },
    { title: "PanAlt", icon: Icons.PanAlt },
    { title: "ParallelAlt", icon: Icons.ParallelAlt },
    { title: "Pause", icon: Icons.Pause },
    { title: "Play", icon: Icons.Play },
    { title: "Plus", icon: Icons.Plus },
    { title: "Point", icon: Icons.Point },
    { title: "PointCloud", icon: Icons.PointCloud },
    { title: "PointCollection", icon: Icons.PointCollection },
    { title: "PointColor", icon: Icons.PointColor },
    { title: "PointInfo", icon: Icons.PointInfo },
    { title: "PointInfoFilled", icon: Icons.PointInfoFilled },
    { title: "Polygon", icon: Icons.Polygon },
    { title: "PolygonCollection", icon: Icons.PolygonCollection },
    { title: "PolygonColor", icon: Icons.PolygonColor },
    { title: "PolygonHole", icon: Icons.PolygonHole },
    { title: "PolygonHoleColor", icon: Icons.PolygonHoleColor },
    { title: "Polyline", icon: Icons.Polyline },
    { title: "PolylineCollection", icon: Icons.PolylineCollection },
    { title: "PolylineColor", icon: Icons.PolylineColor },
    { title: "Print", icon: Icons.Print },
    { title: "ProcessedData", icon: Icons.ProcessedData },
    { title: "Profile", icon: Icons.Profile },
    { title: "Project", icon: Icons.Project },
    { title: "ProjectFolder", icon: Icons.ProjectFolder },
    { title: "ProjectMoveTo", icon: Icons.ProjectMoveTo },
    { title: "Puzzle", icon: Icons.Puzzle },
    { title: "RandomPoint", icon: Icons.RandomPoint },
    { title: "Record", icon: Icons.Record },
    { title: "Rectangle", icon: Icons.Rectangle },
    { title: "Redo", icon: Icons.Redo },
    { title: "Refresh", icon: Icons.Refresh },
    { title: "Rename", icon: Icons.Rename },
    { title: "Reorder", icon: Icons.Reorder },
    { title: "Report", icon: Icons.Report },
    { title: "Reports", icon: Icons.Reports },
    { title: "RestoreData", icon: Icons.RestoreData },
    { title: "Result", icon: Icons.Result },
    { title: "ResultMap", icon: Icons.ResultMap },
    { title: "ReverseLinks", icon: Icons.ReverseLinks },
    { title: "Rewind", icon: Icons.Rewind },
    { title: "Right", icon: Icons.Right },
    { title: "RightCompress", icon: Icons.RightCompress },
    { title: "RightNarrow", icon: Icons.RightNarrow },
    { title: "RightS", icon: Icons.RightS },
    { title: "RotateDevice", icon: Icons.RotateDevice },
    { title: "RotateLeft", icon: Icons.RotateLeft },
    { title: "RotateRight", icon: Icons.RotateRight },
    { title: "Save", icon: Icons.Save },
    { title: "SaveAs", icon: Icons.SaveAs },
    { title: "SeaLevel", icon: Icons.SeaLevel },
    { title: "Search", icon: Icons.Search },
    { title: "Select", icon: Icons.Select },
    { title: "SelectAll", icon: Icons.SelectAll },
    { title: "SelectByAttributes", icon: Icons.SelectByAttributes },
    { title: "SelectByShape", icon: Icons.SelectByShape },
    { title: "SelectionByOperation", icon: Icons.SelectionByOperation },
    { title: "SelectionFiltering", icon: Icons.SelectionFiltering },
    { title: "SelectionManager", icon: Icons.SelectionManager },
    { title: "SelectLayer", icon: Icons.SelectLayer },
    { title: "SelectMultiple", icon: Icons.SelectMultiple },
    { title: "Send", icon: Icons.Send },
    { title: "Server", icon: Icons.Server },
    { title: "Settings", icon: Icons.Settings },
    { title: "Share", icon: Icons.Share },
    { title: "Slow", icon: Icons.Slow },
    { title: "Snapping", icon: Icons.Snapping },
    { title: "SortAlphabetically", icon: Icons.SortAlphabetically },
    { title: "SortAscending", icon: Icons.SortAscending },
    { title: "SortDescending", icon: Icons.SortDescending },
    { title: "Sorticonasc", icon: Icons.Sorticonasc },
    { title: "Sorticondesc", icon: Icons.Sorticondesc },
    { title: "SortReverseAlphabetically", icon: Icons.SortReverseAlphabetically },
    { title: "SpatialProcess", icon: Icons.SpatialProcess },
    { title: "SpatialSelection", icon: Icons.SpatialSelection },
    { title: "Special", icon: Icons.Special },
    { title: "SpecialSelections", icon: Icons.SpecialSelections },
    { title: "SpecialTools", icon: Icons.SpecialTools },
    { title: "Split", icon: Icons.Split },
    { title: "Stop", icon: Icons.Stop },
    { title: "StraightSkeleton", icon: Icons.StraightSkeleton },
    { title: "Subscriptions", icon: Icons.Subscriptions },
    { title: "Sun", icon: Icons.Sun },
    { title: "Support", icon: Icons.Support },
    { title: "SupportAlt", icon: Icons.SupportAlt },
    { title: "SupportAltTwo", icon: Icons.SupportAltTwo },
    { title: "TableResults", icon: Icons.TableResults },
    { title: "TableView", icon: Icons.TableView },
    { title: "Temperature", icon: Icons.Temperature },
    { title: "Terrain3d", icon: Icons.Terrain3d },
    { title: "Terrain3dExaggeration", icon: Icons.Terrain3dExaggeration },
    { title: "Text", icon: Icons.Text },
    { title: "TheissenPolygons", icon: Icons.TheissenPolygons },
    { title: "ThreeD", icon: Icons.ThreeD },
    { title: "TileView", icon: Icons.TileView },
    { title: "Timeline", icon: Icons.Timeline },
    { title: "TimePoint", icon: Icons.TimePoint },
    { title: "ToogleOff", icon: Icons.ToogleOff },
    { title: "ToogleOn", icon: Icons.ToogleOn },
    { title: "Tools", icon: Icons.Tools },
    { title: "TopView", icon: Icons.TopView },
    { title: "Trace", icon: Icons.Trace },
    { title: "TraceLeft", icon: Icons.TraceLeft },
    { title: "TraceRight", icon: Icons.TraceRight },
    { title: "Track", icon: Icons.Track },
    { title: "TwoD", icon: Icons.TwoD },
    { title: "Undo", icon: Icons.Undo },
    { title: "Ungroup", icon: Icons.Ungroup },
    { title: "Unknown", icon: Icons.Unknown },
    { title: "Unlink", icon: Icons.Unlink },
    { title: "Unlock", icon: Icons.Unlock },
    { title: "UnmarkHole", icon: Icons.UnmarkHole },
    { title: "Up", icon: Icons.Up },
    { title: "Upload", icon: Icons.Upload },
    { title: "UploadCloud", icon: Icons.UploadCloud },
    { title: "UpS", icon: Icons.UpS },
    { title: "UpTriangle", icon: Icons.UpTriangle },
    { title: "User", icon: Icons.User },
    { title: "Users", icon: Icons.Users },
    { title: "Validation", icon: Icons.Validation },
    { title: "ValueRange", icon: Icons.ValueRange },
    { title: "Vector", icon: Icons.Vector },
    { title: "VectorOperations", icon: Icons.VectorOperations },
    { title: "Voronoi", icon: Icons.Voronoi },
    { title: "Walking", icon: Icons.Walking },
    { title: "Warning", icon: Icons.Warning },
    { title: "Water", icon: Icons.Water },
    { title: "Wave", icon: Icons.Wave },
    { title: "WizardConfig", icon: Icons.WizardConfig },
    { title: "ZoneMap", icon: Icons.ZoneMap },
    { title: "ZoomIn", icon: Icons.ZoomIn },
    { title: "ZoomOut", icon: Icons.ZoomOut },
    { title: "ZoomToArea", icon: Icons.ZoomToArea },
  ];

  const [filterInput, setFilterInput] = useState("");
  const [filterIcons, setFilterIcons] = useState(iconNames);

  const filter = (e: any) => {
    const keyword = e.target.value;
    if (keyword !== "") {
      const results = iconNames.filter((name) => {
        return name.title.toLowerCase().startsWith(keyword.toLowerCase());
      });
      setFilterIcons(results);
    } else {
      setFilterIcons(iconNames);
    }
    setFilterInput(keyword);
  };

  return (
    <>
      <Head>
        <title>NextJS-Theme-Prototype</title>
      </Head>

      <Typography variant="h1">Icons</Typography>

      <Grid container spacing={0} direction="column" alignItems="center" justifyContent="center">
        <Grid item xs={3}>
          <StyledSearchContainer>
            <TextField
              label=""
              placeholder="Filter Icons"
              value={filterInput}
              size="small"
              onChange={filter}
              variant="standard"
              InputProps={{
                startAdornment: (
                  <InputAdornment position="start">
                    <Icons.Search />
                  </InputAdornment>
                ),
              }}
            />
          </StyledSearchContainer>
        </Grid>
        <Grid item xs={3}>
          <Typography variant="caption">Click an icon to copy it's name to the clipboard</Typography>
        </Grid>
      </Grid>

      <IconGrid>
        {filterIcons && filterIcons.length > 0 ? (
          filterIcons.map((item) => (
            <span key={item.title} title={item.title}>
              <Icon
                component={item.icon}
                className={item.title}
                onClick={() => navigator.clipboard.writeText(item.title)}
              />
              <p>{item.title}</p>
            </span>
          ))
        ) : (
          <Typography variant="h5">No icons found!</Typography>
        )}
      </IconGrid>
    </>
  );
};

export default IconsPage;
